import { useEffect } from 'react';
import Script from 'next/script';
import Head from 'next/head';
import Navbar from './Navbar';
import Footer from './Footer';
import { AuthProvider, useAuth } from '../contexts/AuthContext';
import { useRouter } from 'next/router';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const isDashboard = router.pathname.startsWith('/dashboard'); // Check if the current route is dashboard
  const isLoginPage = router.pathname === '/login'; // Check if the current route is login

  return (
    <>
      <Head>
        <title>AsadTech</title>
        <meta name="Agency Website" content="Generated by AsadTech" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />
      </Head>

      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossOrigin="anonymous"
        strategy="lazyOnload" // Optimize loading strategy
      />

      <AuthProvider>
        {/* Conditionally render Navbar and Footer only if not in the dashboard */}
        {!isDashboard && <Navbar />}

        <AuthGuard isDashboard={isDashboard} isLoginPage={isLoginPage}>
          <div className={isDashboard ? 'dashboard-container' : 'site-container'}>
            <Component {...pageProps} />
          </div>
        </AuthGuard>

        {!isDashboard && <Footer />}
      </AuthProvider>
    </>
  );
}

// AuthGuard component for protecting routes and handling redirection
const AuthGuard = ({ children, isDashboard, isLoginPage }) => {
  const { user, loading } = useAuth(); // Assume useAuth provides user and loading state
  const router = useRouter();

  useEffect(() => {
    // If loading, do nothing
    if (loading) return;

    // If user is logged in and on the login page, redirect to the dashboard
    if (user && isLoginPage) {
      router.push('/dashboard/dashboard');
    }

    // If user is not logged in and trying to access dashboard, redirect to login
    if (!user && isDashboard) {
      router.push('/login');
    }
  }, [loading, user, isDashboard, isLoginPage, router]);

  // While loading, show a loader
  if (loading) {
    return <div>Loading...</div>;
  }

  // If user is on the login page and logged in, don't render login page
  if (isLoginPage && user) {
    return null;
  }

  // Render the content for all other cases
  return children;
};

export default MyApp;
