import { useEffect } from 'react';
import Script from 'next/script';
import Head from 'next/head';
import Navbar from './Navbar';
import Footer from './Footer';
import { AuthProvider, useAuth } from '../contexts/AuthContext';
import { useRouter } from 'next/router';
import '../styles/globals.css';
import { ClipLoader } from 'react-spinners';

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const isDashboard = router.pathname.startsWith('/dashboard'); // Check if the current route is dashboard
  const isLoginPage = router.pathname === '/login'; // Check if the current route is login

  return (
    <>
      <Head>
        <title>AsadTech</title>
        <meta name="Agency Website" content="Generated by AsadTech" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />
      </Head>

      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossOrigin="anonymous"
        strategy="lazyOnload"
      />

      <AuthProvider>
        {/* Conditionally render Navbar and Footer only if not in the dashboard */}
        {!isDashboard && <Navbar />}

        <AuthGuard isDashboard={isDashboard} isLoginPage={isLoginPage}>
          <div className={isDashboard ? 'dashboard-container' : 'site-container'}>
            <Component {...pageProps} />
          </div>
        </AuthGuard>

        {!isDashboard && <Footer />}
      </AuthProvider>
    </>
  );
}

// AuthGuard component for protecting routes and handling redirection
const AuthGuard = ({ children, isDashboard, isLoginPage }) => {
  const { user, loading } = useAuth();
  const router = useRouter();
  useEffect(() => {
    console.log("User:", user);
    console.log("Loading:", loading);
    console.log("Current Route:", router.pathname);
  }, [loading, user, router]);
  
  useEffect(() => {
    if (loading) return; // If loading, don't do anything

    // Only redirect to dashboard if the user is on login page
    if (user && isLoginPage) {
      router.push('/dashboard/dashboard');
      return;
    }

    // Only redirect to login if the user is trying to access dashboard but is not logged in
    if (!user && isDashboard) {
      router.push('/login');
      return;
    }

    // If the user is authenticated and not on login/dashboard, allow them to stay
  }, [loading, user, isDashboard, isLoginPage, router]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <ClipLoader size={80} color={"#36D7B7"} loading={loading} />
      </div>
    );
  }

  return children;
};


export default MyApp;
