import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import MainPage from './MainPage'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
      <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />
        <link
          rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/jodit/4.2.27/jodit.min.css"
        />
        <title>Art Nursing College</title>
        <meta name="Educational Website" content="Generated by Art Nursing College" />
        <meta name="description" content="Welcome to Art Nursing College, a world-class institution offering excellence in nursing education, practice, and research." />
        <meta name="keywords" content="Nursing, Art Nursing College, nursing education, healthcare, nursing practice" />
        <meta name="author" content="Art Nursing College Team" />

        {/* Open Graph / Facebook */}
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Art Nursing College" />
        <meta property="og:description" content="Welcome to Art Nursing College, a world-class institution offering excellence in nursing education, practice, and research." />
        <meta property="og:image" content="https://artncedubd.com/uploads/art-banner.png" />
        <meta property="og:url" content="https://artncedubd.com/" />

        {/* Twitter */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Art Nursing College" />
        <meta name="twitter:description" content="Welcome to Art Nursing College, a world-class institution offering excellence in nursing education, practice, and research." />
        <meta name="twitter:image" content="https://artncedubd.com/uploads/art-banner.png" />
      </Head>
     
      <main className={styles.main}>
        <MainPage/>
      </main>
    </div>
  )
}